### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [wpower12/LGS#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by wpower12** [comment]
It's just up unlicensed. If you have questions i'd be happy to answer them.

**Comment by suprafun** [comment]
Thank you so very much. If its possible, could you please upload any formal license (unlicense, MIT, GPL, whatever you prefer) to the repo. ? That way I (and others who might find it) can be sure of how I should treat this very cool project. Thank you.
